name: DevOps HQ Test

on:
  push:
    branches: [main]

jobs:
  generate ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install cowsay program
        run: sudo apt install cowsay -y

      - name: Execute cowsay cmd
        run: cowsay -f dragon "I'm a Dragon . . ., No mercy !!!" >> dragon.txt

      - name: Check if file created
        run: grep -i "dragon" dragon.txt

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md
