name: DevOps HQ Test

on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "Hello from Github Actions job"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md
